### ISSUE TITLE
Take too long time on saving homes

### ISSUE THREAD

**Issue by david50407** [AdminCMD/AdminCMD#5]
While closing server, AdminCMD saves all homes into database. But this takes 20-30 seconds on my server which has 300 home records.

I read the code of HomeManager and it saves/updates homes by executing a command per home, this can be speed up by using transaction in database (both Sqlite and MySQL supports transaction).

**Comment by TheJeterLP** [comment]
Feel free to contribute and open a pull request, every help is appreciated!

Am 28.04.2017 3:25 nachm. schrieb "David Kuo" <notifications@github.com>:

While closing server, AdminCMD saves all homes into database. But this
takes 20-30 seconds on my server which has 300 home records.

I read the code of HomeManager and it saves/updates homes by executing a
command per home, this can be speed up by using transaction in database
(both Sqlite and MySQL supports transaction).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AdminCMD/AdminCMD/issues/5>, or mute the thread
